name: Smoke tests
on: [push]
jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v1
    - name: Link repository to ~/.dotfiles
      run: |
        ln -sf ${{ github.workspace }} ~/.dotfiles
    - name: Execute full install
      working-directory: ~/.dotfiles
      run: make all
